<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="ejercicio-ii-1c.css"?>
<!-- ejemplodtd1.xml Grupo13 -->
<!DOCTYPE fichero [
        <!ELEMENT fichero (ficha+)>
<!ELEMENT ficha (nombre, apellido, direccion*, DUI?)>
        <!ELEMENT nombre (#PCDATA)>
        <!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
            <!ATTLIST nombre edad  CDATA  #IMPLIED>
        <!ELEMENT apellido (#PCDATA)>
        <!ELEMENT direccion (#PCDATA)>
        <!ELEMENT DUI (#PCDATA)>        ]>
<fichero>
 <ficha>
  <nombre sexo="femenino" edad="22">Blanca</nombre>
  <apellido>Cortez</apellido>
  <direccion>c/Jupiter, 22</direccion>
 </ficha>
</fichero>
